<a href="https://colab.research.google.com/github/sungjindo/python_study/blob/main/ch5_%EB%8F%84%EC%84%B1%EC%A7%84.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**이름: 도성진**

In [ ]:
import numpy as np

## 1. 0 부터 8까지의 값을 순차적으로 갖는 3x3 행렬을 생성하시오

In [ ]:
z = np.matrix(np.arange(9).reshape(3,3))
print(z)
#arange로 바로쓰면 행렬이 아닌 배열?

[[0 1 2]
 [3 4 5]
 [6 7 8]]


## 2.  i번째 열은 원소값으로 모두 (i-1)을 갖는 5x5 행렬을 생성하시오


In [ ]:
z = np.zeros((5,5))
n = np.arange(5)
z += n

In [ ]:
print(z)

[[0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]]


## 3. integer(32 bit) ndarray를 float(32 bit) ndarray로 바꾸려면 어떻게 해야하는가?

In [ ]:
z = np.arange(10, dtype=np.int32)

In [ ]:
z_new = np.float32(z)
print(z_new)

[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]


## 4. quest.pickle 파일에는 5점 만점으로 된 설문조사 결과가 배열로 저장되어 있다. 이 파일을 읽어와서 설문조사 결과 5점 초과하는 값이 있는지 살펴보고 있을 경우 모두 5로 변경하여라. 

In [ ]:
from google.colab import drive

drive.mount('/content/gdrive')
quest = np.load('/content/gdrive/My Drive/data/data/quest.pickle', allow_pickle=True)

Drive already mounted at /content/gdrive; to attempt to forcibly remount, call drive.mount("/content/gdrive", force_remount=True).


In [ ]:
q = quest > 5
quest_new = quest[q]
quest_new[:] = 5

In [ ]:
print(quest_new)
# 이 값을 처음에 quest에 넣어서 하는 방법?

[5 5 5]
